notifications:
  email: false
  slack:
    rooms:
      secure: JZ7Yc/sIRSiHbaXE4eVbXgaxtForUOLvGjqjmIzHw+RGb1psctRaVPH/esvVENjKTsCeXdBNZoJ76t38/RSfwaTfzY/VqNpRPH3V05Lvj/lMojqoj0SGyKZ0crHaS6Wkh1wuizq11Pv18BQI/dQy6H97f9obBD2CJKXuJFw1xk2eTOLDFSERjbP/Tz0VwgN8GuCGuoHK8auoXNO2cGp5LHS/iq3OoRto8zlcOpRs78pF73b1prBeb4ECaQtivtHiLYrpb7egCRft0GQGp6+bRappjfsFlZp9lf9TdqMknbx6K434xGeKbimEglV//D6Uy/s8JY14ajGtJ9fNU9MJ0ffUSksPS+XL561sJSafGKvquTzOvXLGvDR1Z7lJWCv7t4CUDNLfQduJMIeg6mOmOsFRjZek4sydTYHBWmJAKLFDGxV1eakuEc++K5NcP8ehZai0FnF2u23aNRQ37tpdqiypGuTP2RnwMkcgJrbvFqlpdt7lr4j1WeVAzmen1vWDMfvPNANM1pcNTqGkgsQR31hM1ZeogGDCpYQYcUMoq9EPCiSyL14Kb+oBGafLR9U7uf7fUZevlqcR1IDHz0tZLec1s0MgHkur0Qq+WBYr61H9QCBNLRrzu5gxO5ftlCoqMxWD3rMtEzoP9WkJcSVpBteSrcgqQXbarMQyXn9OBw0=
    on_success: always
    on_failure: always
stages:
- name: PUBLISH
jobs:
  include:
  - stage: PUBLISH
    language: node_js
    node_js:
    - '12'
    install: true
    script: cd docs && yarn install && yarn build
    deploy:
      provider: pages
      local-dir: docs/.vuepress/dist
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      on:
        branch: master
